# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo AZURE_WEBAPP_PUBLISH_PROFILE=${AZURE_WEBAPP_PUBLISH_PROFILE}
    echo AZP_TOKEN: ${AZP_TOKEN}
    echo GITHUB_TOKEN: ${GITHUB_TOKEN}
  displayName: 'Run a multi-line script'
  env:
    AZP_TOKEN: ${{ secrets.AZP_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}